### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by sulibs** [kuchiki-rs/kuchiki#15] opened 2015-10-17 22:49 UTC
I can't compile kuchiki, I get the same error when i try to add selectors to cargo.toml, so maybe that is where the problem lies. I am using the nightly builds (1.5)

Below is the error I'm getting when running: cargo build --verbose

unable to get packages from source

Caused by:
  Failed to unpack package `kuchiki v0.0.1`

Caused by:
  No such file or directory (os error 2)

**Comment by SimonSapin** [comment] 2015-10-18 01:46
I could not reproduce this. Are you running Cargo in a clone of Kuchiki’s repository, or in your own crate with Kuchiki as a dependencies? Note that Kuchiki is not published on crates.io (other than an empty version to reserve the name), you need to use `kuchiki = { git = "https://github.com/SimonSapin/kuchiki" }` in `Cargo.toml`. Please provide step-by-step instructions of what you’re doing to reproduce the issue, for example starting with `cargo new foo`. Also, if you’re on Linux, try running `strace -e file cargo build` to see what file or directory is not found. Hopefully it should be an `open` call near the end. (strace will likely print a _lot_ of output.)

**Comment by sulibs** [comment] 2015-10-18 11:06
Thanks! I'm on OS X El Capitan, but in my Cargo.toml i had kuchiki = "*" so i guess that's the problem. Sorry for wasting your time, I'm a noob at this and come from a web background. And I haven't tried kuchiki yet though, but nice work.

**Comment by SimonSapin** [comment] 2015-10-18 11:09
No worries! Closing as `kuchiki = { git = "https://github.com/SimonSapin/kuchiki" }` should (hopefully) work for you.

**Comment by sulibs** [comment] 2015-10-18 11:11
It did. Thanks again. :)

**Closed as completed** 2015-10-18 11:15 UTC

**Comment by SimonSapin** [comment] 2015-10-28 04:51
I’ve published https://crates.io/crates/kuchiki v0.1.0
